
###############################################################################
#
# Inclusive Makefile for the p4ns_common module.
#
# Autogenerated 2014-11-19 18:23:24.283760
#
###############################################################################
p4ns_common_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(p4ns_common_BASEDIR)/module/make.mk
include $(p4ns_common_BASEDIR)/module/src/make.mk
include $(p4ns_common_BASEDIR)/module/auto/make.mk
include $(p4ns_common_BASEDIR)/utest/_make.mk

